# deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-deployment
  labels:
    app: {{ .Values.server.b.name }}
spec:
  replicas: {{ .Values.server.b.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.b.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.b.name }}
    spec:
      containers:
        - name: {{ .Values.server.b.name }}
          image: {{ .Values.server.b.image }}
          imagePullPolicy: IfNotPresent     # 在kind中需要指定，不然会强制到远程拉取镜像，导致部署失败
          ports:
            - containerPort: 80
          volumeMounts: # 映射文件为宿主机文件
            - mountPath: /log/
              name: log
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
        - name: log
          hostPath:
            path: /log/
---
# service 配置
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.b.name }}
  labels:
    app: {{ .Values.server.b.name }}  # 只有设置label,才能被服务发现找到
spec:
  selector:
    app: {{ .Values.server.b.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80