apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tls-secret
data:
  tls.crt: {{ $.Files.Get "tls/alber.com.pem" | b64enc }}
  tls.key: {{ $.Files.Get "tls/alber.com.key" | b64enc }}