// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: a.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequestA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequestA) Reset() {
	*x = HelloRequestA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequestA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestA) ProtoMessage() {}

func (x *HelloRequestA) ProtoReflect() protoreflect.Message {
	mi := &file_a_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestA.ProtoReflect.Descriptor instead.
func (*HelloRequestA) Descriptor() ([]byte, []int) {
	return file_a_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequestA) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReplyA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReplyA) Reset() {
	*x = HelloReplyA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReplyA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReplyA) ProtoMessage() {}

func (x *HelloReplyA) ProtoReflect() protoreflect.Message {
	mi := &file_a_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReplyA.ProtoReflect.Descriptor instead.
func (*HelloReplyA) Descriptor() ([]byte, []int) {
	return file_a_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReplyA) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_a_proto protoreflect.FileDescriptor

var file_a_proto_rawDesc = []byte{
	0x0a, 0x07, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x61, 0x22, 0x23, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x41, 0x0a, 0x01, 0x41, 0x12, 0x3c, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x61, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x1a, 0x16, 0x2e,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x61, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x41, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_a_proto_rawDescOnce sync.Once
	file_a_proto_rawDescData = file_a_proto_rawDesc
)

func file_a_proto_rawDescGZIP() []byte {
	file_a_proto_rawDescOnce.Do(func() {
		file_a_proto_rawDescData = protoimpl.X.CompressGZIP(file_a_proto_rawDescData)
	})
	return file_a_proto_rawDescData
}

var file_a_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_a_proto_goTypes = []interface{}{
	(*HelloRequestA)(nil), // 0: default.a.HelloRequestA
	(*HelloReplyA)(nil),   // 1: default.a.HelloReplyA
}
var file_a_proto_depIdxs = []int32{
	0, // 0: default.a.A.SayHello:input_type -> default.a.HelloRequestA
	1, // 1: default.a.A.SayHello:output_type -> default.a.HelloReplyA
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_a_proto_init() }
func file_a_proto_init() {
	if File_a_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_a_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequestA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_a_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReplyA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_a_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a_proto_goTypes,
		DependencyIndexes: file_a_proto_depIdxs,
		MessageInfos:      file_a_proto_msgTypes,
	}.Build()
	File_a_proto = out.File
	file_a_proto_rawDesc = nil
	file_a_proto_goTypes = nil
	file_a_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AClient is the client API for A service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequestA, opts ...grpc.CallOption) (*HelloReplyA, error)
}

type aClient struct {
	cc grpc.ClientConnInterface
}

func NewAClient(cc grpc.ClientConnInterface) AClient {
	return &aClient{cc}
}

func (c *aClient) SayHello(ctx context.Context, in *HelloRequestA, opts ...grpc.CallOption) (*HelloReplyA, error) {
	out := new(HelloReplyA)
	err := c.cc.Invoke(ctx, "/default.a.A/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AServer is the server API for A service.
type AServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequestA) (*HelloReplyA, error)
}

// UnimplementedAServer can be embedded to have forward compatible implementations.
type UnimplementedAServer struct {
}

func (*UnimplementedAServer) SayHello(context.Context, *HelloRequestA) (*HelloReplyA, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterAServer(s *grpc.Server, srv AServer) {
	s.RegisterService(&_A_serviceDesc, srv)
}

func _A_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequestA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/default.a.A/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AServer).SayHello(ctx, req.(*HelloRequestA))
	}
	return interceptor(ctx, in, info, handler)
}

var _A_serviceDesc = grpc.ServiceDesc{
	ServiceName: "default.a.A",
	HandlerType: (*AServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _A_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a.proto",
}
