// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: b.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequestB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequestB) Reset() {
	*x = HelloRequestB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_b_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequestB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestB) ProtoMessage() {}

func (x *HelloRequestB) ProtoReflect() protoreflect.Message {
	mi := &file_b_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestB.ProtoReflect.Descriptor instead.
func (*HelloRequestB) Descriptor() ([]byte, []int) {
	return file_b_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequestB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReplyB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReplyB) Reset() {
	*x = HelloReplyB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_b_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReplyB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReplyB) ProtoMessage() {}

func (x *HelloReplyB) ProtoReflect() protoreflect.Message {
	mi := &file_b_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReplyB.ProtoReflect.Descriptor instead.
func (*HelloReplyB) Descriptor() ([]byte, []int) {
	return file_b_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReplyB) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_b_proto protoreflect.FileDescriptor

var file_b_proto_rawDesc = []byte{
	0x0a, 0x07, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x62, 0x22, 0x23, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x41, 0x0a, 0x01, 0x42, 0x12, 0x3c, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x1a, 0x16, 0x2e,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_b_proto_rawDescOnce sync.Once
	file_b_proto_rawDescData = file_b_proto_rawDesc
)

func file_b_proto_rawDescGZIP() []byte {
	file_b_proto_rawDescOnce.Do(func() {
		file_b_proto_rawDescData = protoimpl.X.CompressGZIP(file_b_proto_rawDescData)
	})
	return file_b_proto_rawDescData
}

var file_b_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_b_proto_goTypes = []interface{}{
	(*HelloRequestB)(nil), // 0: default.b.HelloRequestB
	(*HelloReplyB)(nil),   // 1: default.b.HelloReplyB
}
var file_b_proto_depIdxs = []int32{
	0, // 0: default.b.B.SayHello:input_type -> default.b.HelloRequestB
	1, // 1: default.b.B.SayHello:output_type -> default.b.HelloReplyB
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_b_proto_init() }
func file_b_proto_init() {
	if File_b_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_b_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequestB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_b_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReplyB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_b_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_b_proto_goTypes,
		DependencyIndexes: file_b_proto_depIdxs,
		MessageInfos:      file_b_proto_msgTypes,
	}.Build()
	File_b_proto = out.File
	file_b_proto_rawDesc = nil
	file_b_proto_goTypes = nil
	file_b_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BClient is the client API for B service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequestB, opts ...grpc.CallOption) (*HelloReplyB, error)
}

type bClient struct {
	cc grpc.ClientConnInterface
}

func NewBClient(cc grpc.ClientConnInterface) BClient {
	return &bClient{cc}
}

func (c *bClient) SayHello(ctx context.Context, in *HelloRequestB, opts ...grpc.CallOption) (*HelloReplyB, error) {
	out := new(HelloReplyB)
	err := c.cc.Invoke(ctx, "/default.b.B/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BServer is the server API for B service.
type BServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequestB) (*HelloReplyB, error)
}

// UnimplementedBServer can be embedded to have forward compatible implementations.
type UnimplementedBServer struct {
}

func (*UnimplementedBServer) SayHello(context.Context, *HelloRequestB) (*HelloReplyB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterBServer(s *grpc.Server, srv BServer) {
	s.RegisterService(&_B_serviceDesc, srv)
}

func _B_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequestB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/default.b.B/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BServer).SayHello(ctx, req.(*HelloRequestB))
	}
	return interceptor(ctx, in, info, handler)
}

var _B_serviceDesc = grpc.ServiceDesc{
	ServiceName: "default.b.B",
	HandlerType: (*BServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _B_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "b.proto",
}
